vasm6502_oldstyle -Fbin dasblink.asm         -dotdir -o dasblink.bin
vasm6502_oldstyle -Fbin cylons.asm           -dotdir -o cylons.bin
vasm6502_oldstyle -Fbin mvleft.asm           -dotdir -o mvleft.bin
vasm6502_oldstyle -Fbin noise.asm            -dotdir -o noise.bin
vasm6502_oldstyle -Fbin dasblink2.asm        -dotdir -o dasblink2.bin
vasm6502_oldstyle -Fbin lcd_hello_world.asm  -dotdir -o lcd_hello_world.bin
vasm6502_oldstyle -Fbin junk_scroll.asm      -dotdir -o junk_scroll.bin
vasm6502_oldstyle -Fbin cursor_test.asm      -dotdir -o cursor_test.bin
vasm6502_oldstyle -Fbin happy_trees.asm      -dotdir -o happy_trees.bin
vasm6502_oldstyle -Fbin testram.asm          -dotdir -o testram.bin
vasm6502_oldstyle -Fbin happy_trees_ram.asm  -dotdir -o happy_trees_ram.bin
vasm6502_oldstyle -Fbin num_display.asm      -dotdir -o num_display.bin
vasm6502_oldstyle -Fbin final_count_down.asm -dotdir -o final_count_down.bin
vasm6502_oldstyle -Fbin fcd_int.asm          -dotdir -o fcd_int.bin
vasm6502_oldstyle -Fbin fcd_int_4pins.asm    -dotdir -o fcd_int_4pins.bin
