vasm6502_oldstyle -Fbin dasblink.asm         -dotdir -o dasblink.bin
vasm6502_oldstyle -Fbin cylons.asm           -dotdir -o cylons.bin
vasm6502_oldstyle -Fbin mvleft.asm           -dotdir -o mvleft.bin
vasm6502_oldstyle -Fbin noise.asm            -dotdir -o noise.bin
vasm6502_oldstyle -Fbin dasblink2.asm        -dotdir -o dasblink2.bin
vasm6502_oldstyle -Fbin lcd_hello_world.asm  -dotdir -o lcd_hello_world.bin
vasm6502_oldstyle -Fbin junk_scroll.asm      -dotdir -o junk_scroll.bin
vasm6502_oldstyle -Fbin cursor_test.asm      -dotdir -o cursor_test.bin
vasm6502_oldstyle -Fbin happy_trees.asm      -dotdir -o happy_trees.bin
